"use strict";
(function () {
  const parts = [
    { type: "gpu", icon: "◈", name: "NVIDIA GeForce RTX 5070", brand: "NVIDIA / Blackwell", spec: "12GB GDDR7 · 1440p Ultra", score: 92, price: "از ۵۹ میلیون تومان", badge: "انتخاب متعادل" },
    { type: "gpu", icon: "◈", name: "AMD Radeon RX 9070 XT", brand: "AMD / RDNA 4", spec: "16GB GDDR6 · 4K Ready", score: 94, price: "از ۶۷ میلیون تومان", badge: "ارزش خرید بالا" },
    { type: "cpu", icon: "⬡", name: "AMD Ryzen 7 9800X3D", brand: "AMD / AM5", spec: "8 هسته · 16 رشته · 3D V-Cache", score: 97, price: "از ۳۹ میلیون تومان", badge: "بهترین برای گیم" },
    { type: "cpu", icon: "⬡", name: "Intel Core Ultra 7 265K", brand: "Intel / LGA1851", spec: "20 هسته · NPU · DDR5", score: 88, price: "از ۳۵ میلیون تومان", badge: "همه‌کاره" },
    { type: "monitor", icon: "▣", name: "LG UltraGear OLED 27GS", brand: "LG / OLED", spec: "27 اینچ · QHD · 240Hz", score: 95, price: "از ۵۲ میلیون تومان", badge: "تجربه پریمیوم" },
    { type: "peripheral", icon: "⌁", name: "Logitech G Pro X 2", brand: "Logitech / Wireless", spec: "هدفون گیمینگ · 50 ساعت شارژ", score: 90, price: "از ۱۴ میلیون تومان", badge: "رقابتی" }
  ];
  const labels = { gpu: "GPU", cpu: "CPU", monitor: "DISPLAY", peripheral: "GEAR" };
  const grid = document.getElementById("hardwareGrid"); const search = document.getElementById("hardwareSearch"); let filter = "all";
  function render() { const query = (search?.value || "").trim().toLowerCase(); const result = parts.filter(item => (filter === "all" || item.type === filter) && (!query || `${item.name} ${item.brand} ${item.spec}`.toLowerCase().includes(query))); grid.replaceChildren(); if (!result.length) { const empty = document.createElement("p"); empty.className = "hardware-empty"; empty.textContent = "قطعه‌ای با این مشخصات پیدا نشد."; grid.append(empty); return; } result.forEach(item => { const card = document.createElement("article"); card.className = "hardware-card"; card.innerHTML = `<div class="hardware-card__top"><span class="hardware-card__icon">${item.icon}</span><span class="hardware-card__type">${labels[item.type]}</span></div><span class="hardware-card__badge">${item.badge}</span><h3>${item.name}</h3><p class="hardware-card__brand">${item.brand}</p><p class="hardware-card__spec">${item.spec}</p><div class="hardware-card__bottom"><span>${item.price}</span><b>${item.score}<small>/100</small></b></div>`; grid.append(card); }); }
  document.querySelectorAll(".filter-button").forEach(button => button.addEventListener("click", () => { filter = button.dataset.filter; document.querySelectorAll(".filter-button").forEach(item => item.classList.toggle("is-active", item === button)); render(); })); search?.addEventListener("input", render);
  const builds = { gaming: "Ryzen 7 9800X3D + RTX 5070 + مانیتور QHD 240Hz؛ تمرکز روی فریم‌ریت بالا و تأخیر کم.", creator: "Core Ultra 7 265K + RX 9070 XT + 32GB DDR5؛ مناسب تدوین، رندر و استریم.", balanced: "Ryzen 7 9800X3D + RTX 5070 + SSD NVMe؛ انتخاب متعادل برای بازی و کار روزانه." }; document.querySelectorAll("[data-build]").forEach(button => button.addEventListener("click", () => { document.querySelectorAll("[data-build]").forEach(item => item.classList.toggle("is-selected", item === button)); document.getElementById("buildResult").textContent = builds[button.dataset.build]; })); render();
}());
