"use strict";
document.addEventListener("DOMContentLoaded", () => {
  const form = document.getElementById("publishForm"), input = document.getElementById("imageInput"), preview = document.getElementById("imagePreview"), box = document.getElementById("uploadBox"), status = document.getElementById("publishStatus"), category = document.getElementById("category");
  const setStatus = (message, error = false) => { status.textContent = message; status.classList.toggle("error", error); };
  const syncPreview = () => { document.getElementById("previewTitle").textContent = document.getElementById("title").value.trim() || "عنوان خبر"; const previewGame = document.getElementById("previewGame"); if (previewGame) previewGame.textContent = `بازی یا موضوع: ${document.getElementById("game").value.trim() || "—"}`; document.getElementById("previewExcerpt").textContent = document.getElementById("excerpt").value.trim() || document.getElementById("text").value.trim().slice(0, 160) || "خلاصه خبر اینجا نمایش داده می‌شود."; document.getElementById("previewCategory").textContent = category.options[category.selectedIndex].text; const tags = document.getElementById("tags").value.match(/#[^\s#]+/g) || []; document.getElementById("previewTags").innerHTML = tags.map(tag => `<span>${escapeHtml(tag)}</span>`).join(""); const official = document.getElementById("previewOfficial"); if (official) official.hidden = !(getUser()?.role === "admin"); const author = document.querySelector(".preview-author"); if (author) author.textContent = `نویسنده: ${getUser()?.name || "شما"}`; };
  const readImage = file => { if (!file) return Promise.resolve(""); if (!/^image\/(png|jpeg|webp)$/.test(file.type)) return Promise.reject(new Error("فرمت تصویر باید PNG، JPG یا WebP باشد.")); if (file.size > 650000) return Promise.reject(new Error("حجم تصویر باید کمتر از ۶۵۰ کیلوبایت باشد.")); return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error("خواندن تصویر ناموفق بود.")); reader.readAsDataURL(file); }); };
  input.addEventListener("change", async () => { try { const src = await readImage(input.files[0]); preview.src = src; preview.hidden = !src; box.querySelector(".upload-icon").hidden = !!src; box.querySelector("strong").textContent = src ? "تصویر انتخاب شد" : "انتخاب تصویر"; document.getElementById("previewImage").innerHTML = src ? `<img src="${src}" alt="">` : ""; setStatus(""); } catch (error) { input.value = ""; setStatus(error.message, true); } });
  document.getElementById("changeImage").addEventListener("click", () => input.click());
  document.getElementById("removeImage").addEventListener("click", () => { input.value = ""; preview.hidden = true; box.querySelector(".upload-icon").hidden = false; box.querySelector("strong").textContent = "انتخاب تصویر"; document.getElementById("previewImage").replaceChildren(); });
  ["title", "game", "excerpt", "text", "tags", "category"].forEach(id => document.getElementById(id).addEventListener("input", syncPreview));
  form.addEventListener("submit", async event => { event.preventDefault(); const user = getUser(); if (!user) { location.href = "login.html"; return; } const button = document.getElementById("publishButton"); button.disabled = true; setStatus("در حال انتشار..."); try { const image = await readImage(input.files[0]); const result = await PERFASHINALRequest("/news", { method: "POST", body: JSON.stringify({ title: document.getElementById("title").value, game: document.getElementById("game").value, excerpt: document.getElementById("excerpt").value, text: document.getElementById("text").value, category: category.value, tags: document.getElementById("tags").value, image }) }); setStatus("خبر با موفقیت منتشر شد؛ در حال انتقال..."); setTimeout(() => { location.href = `news-detail.html?id=${encodeURIComponent(result.news.id)}`; }, 500); } catch (error) { setStatus(error.message, true); button.disabled = false; } });
  document.getElementById("previewButton").addEventListener("click", () => { syncPreview(); document.getElementById("previewPanel").scrollIntoView({ behavior: "smooth", block: "nearest" });
});

});
