import {useEffect,useState} from 'react';
import {Edit3,Trash2,ShieldBan,ShieldCheck} from 'lucide-react';
import GlassCard from '../components/GlassCard';import {adminApi,newsAdminApi} from '../services/api';import {Loading,ErrorState,Empty} from '../components/States';import {useToast} from '../context/ToastContext';
const emptyNews={title:'',excerpt:'',body:'',category:'Gaming',featured:false,published:true};
export default function Admin(){const [stats,setStats]=useState(null),[pending,setPending]=useState(null),[users,setUsers]=useState([]),[reports,setReports]=useState([]),[logs,setLogs]=useState([]),[news,setNews]=useState([]),[form,setForm]=useState(emptyNews),[editing,setEditing]=useState(null),[e,setE]=useState(''),toast=useToast();
 const load=async()=>{setE('');try{const [a,b,c,d,l,u]=await Promise.all([adminApi.stats(),adminApi.pending(),adminApi.reports(),newsAdminApi.list(),adminApi.logs(),adminApi.users()]);setStats(a.stats);setPending(b.users);setReports(c.reports);setNews(d.items);setLogs(l.logs||[]);setUsers(u.users||[])}catch(x){setE(x.message)}};useEffect(()=>{load()},[]);
 const action=async(id,ok)=>{try{await adminApi.approve(id,ok);setPending(p=>p.filter(x=>x.id!==id));toast.success(ok?'کاربر تأیید شد.':'کاربر رد شد.')}catch(x){toast.error(x.message)}};
 const userStatus=async(u)=>{try{if(u.status==='blocked')await adminApi.unblockUser(u.id);else await adminApi.blockUser(u.id);await load();toast.success('وضعیت کاربر تغییر کرد.')}catch(x){toast.error(x.message)}};
 const submitNews=async ev=>{ev.preventDefault();try{if(editing)await newsAdminApi.update(editing,form);else await newsAdminApi.create(form);setForm(emptyNews);setEditing(null);await load();toast.success(editing?'خبر ویرایش شد.':'خبر منتشر شد.')}catch(x){toast.error(x.message)}};
 const removeNews=async id=>{if(!confirm('حذف خبر قطعی است؟'))return;try{await newsAdminApi.remove(id);setNews(v=>v.filter(n=>n.id!==id));toast.success('خبر حذف شد.')}catch(x){toast.error(x.message)}};
 if(e)return <ErrorState message={e} onRetry={load}/>;if(!stats||!pending)return <Loading/>;return <div className="space-y-6"><h1 className="text-3xl font-black">پنل مدیریت</h1><div className="grid gap-4 sm:grid-cols-5">{[['کاربران',stats.users],['در انتظار',stats.pending],['گروه‌ها',stats.groups],['گزارش باز',stats.openReports],['اخبار',stats.news]].map(([l,v])=><GlassCard key={l}><b className="text-2xl">{v}</b><p className="mt-1 text-slate-400">{l}</p></GlassCard>)}</div>
 <GlassCard><h2 className="text-xl font-bold">ثبت‌نام‌های در انتظار</h2>{pending.length===0?<Empty label="درخواستی وجود ندارد."/>:<div className="mt-4 space-y-2">{pending.map(u=><div key={u.id} className="flex flex-col gap-2 rounded-2xl bg-white/5 p-4 md:flex-row md:items-center md:justify-between"><div><b>{u.displayName}</b><p className="text-sm text-slate-400">@{u.username} · {u.email}</p></div><div className="flex gap-2"><button onClick={()=>action(u.id,true)} className="rounded-xl bg-emerald-300 px-3 py-2 text-xs font-bold text-slate-950">تأیید</button><button onClick={()=>action(u.id,false)} className="rounded-xl border border-rose-300/20 px-3 py-2 text-xs text-rose-200">رد</button></div></div>)}</div>}</GlassCard>
 <GlassCard><h2 className="text-xl font-bold">مدیریت کاربران</h2>{users.length===0?<Empty label="کاربری نیست."/>:<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b border-white/10 text-right text-slate-500"><th className="p-3">کاربر</th><th className="p-3">نقش</th><th className="p-3">وضعیت</th><th className="p-3">امتیاز</th><th className="p-3">عملیات</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-b border-white/5"><td className="p-3"><b>{u.displayName}</b><div className="text-xs text-slate-500">@{u.username}</div></td><td className="p-3">{u.role}</td><td className="p-3">{u.status}</td><td className="p-3">{u.score}</td><td className="p-3">{u.status==='blocked'?<button onClick={()=>userStatus(u)} className="inline-flex items-center gap-1 text-emerald-300"><ShieldCheck size={15}/> رفع مسدودی</button>:<button disabled={u.role==='admin'} onClick={()=>userStatus(u)} className="inline-flex items-center gap-1 text-rose-300 disabled:opacity-40"><ShieldBan size={15}/> مسدود</button>}</td></tr>)}</tbody></table></div>}</GlassCard>
 <GlassCard><h2 className="text-xl font-bold">گزارش‌ها</h2>{reports.length===0?<Empty label="گزارش بازی وجود ندارد."/>:<div className="mt-4 space-y-2">{reports.map(r=><div key={r.id} className="flex flex-col gap-2 rounded-2xl bg-white/5 p-4 md:flex-row md:items-center md:justify-between"><div><b>{r.kind}</b><p className="text-sm text-slate-400">{r.reason} · توسط @{r.reporter} · هدف: {r.target_id}</p></div><button onClick={async()=>{try{await adminApi.closeReport(r.id);setReports(x=>x.filter(y=>y.id!==r.id));toast.success('گزارش بسته شد.')}catch(x){toast.error(x.message)}}} className="rounded-xl border border-white/10 px-3 py-2 text-sm">بستن</button></div>)}</div>}</GlassCard>
 <GlassCard><h2 className="text-xl font-bold">لاگ‌های مهم</h2>{logs.length===0?<Empty label="هنوز لاگی ثبت نشده."/>:<div className="mt-4 space-y-2">{logs.map(l=><div key={l.id} className="rounded-2xl bg-white/5 p-3"><div className="flex items-center justify-between gap-3"><b className="text-sm">{l.type}</b><span className="text-[10px] text-slate-500">{new Date(l.createdAt).toLocaleString('fa-IR')}</span></div><pre className="mt-2 overflow-auto text-[10px] text-slate-400">{JSON.stringify(l.meta)}</pre></div>)}</div>}</GlassCard>
 <GlassCard><div className="flex items-center justify-between"><h2 className="text-xl font-bold">مدیریت اخبار</h2>{editing&&<button onClick={()=>{setEditing(null);setForm(emptyNews)}} className="text-sm text-slate-400">لغو ویرایش</button>}</div><form onSubmit={submitNews} className="mt-4 grid gap-3"><input required value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))} placeholder="عنوان" className="rounded-2xl border border-white/10 bg-white/5 px-3 py-3"/><input required value={form.excerpt} onChange={e=>setForm(v=>({...v,excerpt:e.target.value}))} placeholder="خلاصه" className="rounded-2xl border border-white/10 bg-white/5 px-3 py-3"/><textarea required value={form.body} onChange={e=>setForm(v=>({...v,body:e.target.value}))} placeholder="متن کامل" className="min-h-36 rounded-2xl border border-white/10 bg-white/5 p-3"/><div className="grid gap-3 sm:grid-cols-3"><select value={form.category} onChange={e=>setForm(v=>({...v,category:e.target.value}))} className="rounded-2xl border border-white/10 bg-white/5 px-3 py-3">{['Gaming','Esports','Hardware','Updates'].map(x=><option key={x}>{x}</option>)}</select><label className="flex items-center gap-2 rounded-2xl border border-white/10 px-3"><input type="checkbox" checked={form.featured} onChange={e=>setForm(v=>({...v,featured:e.target.checked}))}/> ویژه</label><label className="flex items-center gap-2 rounded-2xl border border-white/10 px-3"><input type="checkbox" checked={form.published} onChange={e=>setForm(v=>({...v,published:e.target.checked}))}/> منتشرشده</label></div><button className="rounded-2xl bg-cyan-300 py-3 font-bold text-slate-950">{editing?'ذخیره تغییرات':'انتشار خبر'}</button></form><div className="mt-6 space-y-2">{news.map(n=><div key={n.id} className="flex flex-col gap-3 rounded-2xl bg-white/5 p-4 md:flex-row md:items-center md:justify-between"><div><b>{n.title}</b><p className="text-xs text-slate-500">{n.category} · {n.featured?'ویژه':'معمولی'} · {n.published?'منتشر':'پیش‌نویس'}</p></div><div className="flex gap-2"><button onClick={()=>{setEditing(n.id);setForm({title:n.title,excerpt:n.excerpt,body:n.body,category:n.category,featured:n.featured,published:n.published})}} className="inline-flex items-center gap-1 rounded-xl border border-white/10 px-3 py-2 text-xs"><Edit3 size={14}/> ویرایش</button><button onClick={()=>removeNews(n.id)} className="inline-flex items-center gap-1 rounded-xl border border-rose-300/20 px-3 py-2 text-xs text-rose-200"><Trash2 size={14}/> حذف</button></div></div>)}</div></GlassCard>
 </div>}
