create extension if not exists pgcrypto;
create table if not exists users(id uuid primary key default gen_random_uuid(),username varchar(24) unique not null,display_name varchar(60) not null,email varchar(160) unique not null,password_hash text not null,bio varchar(500),favorite_game varchar(80),role varchar(20) not null default 'user' check(role in ('user','moderator','admin')),status varchar(20) not null default 'pending' check(status in ('pending','approved','rejected','blocked')),score integer not null default 0,level integer not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists sessions(id bigserial primary key,user_id uuid not null references users(id) on delete cascade,jti text unique not null,token_hash text not null,expires_at timestamptz not null,created_at timestamptz not null default now());
create table if not exists follows(follower_id uuid not null references users(id) on delete cascade,following_id uuid not null references users(id) on delete cascade,created_at timestamptz not null default now(),primary key(follower_id,following_id));
create table if not exists news(id uuid primary key default gen_random_uuid(),title varchar(220) not null,excerpt varchar(500) not null,body text not null,category varchar(30) not null check(category in ('Gaming','Esports','Hardware','Updates')),author_id uuid references users(id),published boolean not null default true,likes integer not null default 0,created_at timestamptz not null default now());
create table if not exists news_likes(news_id uuid not null references news(id) on delete cascade,user_id uuid not null references users(id) on delete cascade,primary key(news_id,user_id));
create table if not exists comments(id uuid primary key default gen_random_uuid(),news_id uuid not null references news(id) on delete cascade,user_id uuid not null references users(id) on delete cascade,text varchar(500) not null,created_at timestamptz not null default now());
create table if not exists groups(id uuid primary key default gen_random_uuid(),name varchar(80) not null,description varchar(500) not null,is_private boolean not null default false,owner_id uuid not null references users(id),created_at timestamptz not null default now());
create table if not exists group_members(group_id uuid not null references groups(id) on delete cascade,user_id uuid not null references users(id) on delete cascade,status varchar(20) not null default 'pending' check(status in ('pending','approved','rejected')),role varchar(20) not null default 'member' check(role in ('member','moderator','owner')),joined_at timestamptz not null default now(),primary key(group_id,user_id));
create index if not exists idx_users_status on users(status);create index if not exists idx_news_created on news(created_at desc);create index if not exists idx_news_category on news(category);create index if not exists idx_comments_news_created on comments(news_id,created_at desc);create index if not exists idx_group_members_user on group_members(user_id);create index if not exists idx_sessions_user on sessions(user_id);create index if not exists idx_follows_following on follows(following_id);

create table if not exists notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references users(id) on delete cascade,type varchar(40) not null,title varchar(160) not null,body varchar(500) not null,read_at timestamptz,created_at timestamptz not null default now());
create table if not exists reports(id uuid primary key default gen_random_uuid(),kind varchar(30) not null check(kind in ('message','user','news','group')),target_id text not null,reporter_id uuid not null references users(id) on delete cascade,reason varchar(500) not null,status varchar(20) not null default 'open' check(status in ('open','closed')),created_at timestamptz not null default now(),resolved_at timestamptz);
create index if not exists idx_notifications_user_created on notifications(user_id,created_at desc);create index if not exists idx_notifications_unread on notifications(user_id,read_at);create index if not exists idx_reports_status_created on reports(status,created_at desc);

create table if not exists friend_requests(id uuid primary key default gen_random_uuid(),sender_id uuid not null references users(id) on delete cascade,receiver_id uuid not null references users(id) on delete cascade,status varchar(20) not null default 'pending' check(status in ('pending','accepted','rejected')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(sender_id,receiver_id));
create table if not exists blocks(blocker_id uuid not null references users(id) on delete cascade,blocked_id uuid not null references users(id) on delete cascade,created_at timestamptz not null default now(),primary key(blocker_id,blocked_id));
create index if not exists idx_friend_receiver_status on friend_requests(receiver_id,status);create index if not exists idx_friend_sender_status on friend_requests(sender_id,status);create index if not exists idx_blocks_blocked on blocks(blocked_id);
